apiVersion: v2
name: firmirror
description: A Helm chart for Firmirror - LVFS-compatible firmware repository sync
type: application
version: 0.2.1
appVersion: 0.2.1
keywords:
- lvfs
- fwupd
maintainers:
- name: Criteo
