apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "firmirror.fullname" . }}
  labels:
    {{- include "firmirror.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid # could cause metadata corruption
  jobTemplate:
    metadata:
      labels:
        {{- include "firmirror.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "firmirror.jobSpec" (dict "root" . "args" (include "firmirror.args" .) "resources" .Values.resources "deadline" .Values.cronjob.activeDeadlineSeconds) | nindent 6 }}
